### PR TITLE
fix: serve file cros

### PR DESCRIPTION
**Pull request by wssgcg1213**
for sanhan's problem

### CODE REVIEW

**Comment by wssgcg1213** [comment]
font file follow cros rules, so we should provide cros in dev-server

**Comment by wssgcg1213** [comment]
for def publish, we may provide metafile to enable cros in alicdn, but security problem should be considered

**Comment by wssgcg1213** [comment]
need a further discussion

**Comment by noyobo** [comment]
cdn 具备字体文件 cors 能力

**Pull request merged**
