### PR TITLE
feat: loading && error UI

### PR DESCRIPTION
**Pull request by alvinhui**
Loading UI:

loading

Error UI:

error

### CODE REVIEW

**Comment by alvinhui** [comment]
Display loading log and error message should be better.

**Comment by alvinhui** [comment]
@zhaofeng-shu33 

- Display loading logs and error message should be better;
- No loading page is displayed when exit app, please check;

**Comment by zhaofeng-shu33** [comment]
> @zhaofeng-shu33
> 
> * Display loading logs and error message should be better;
> * No loading page is displayed when exit app, please check;

The existing is immediate. Do we need a dialog for user to confirm existing?

**Comment by alvinhui** [comment]
> The existing is immediate. Do we need a dialog for user to confirm existing?

I don't think so. User exit will be a deterministic operation, such as command+Q.

**Comment by zhaofeng-shu33** [comment]
> > The existing is immediate. Do we need a dialog for user to confirm existing?
> 
> I don't think so. User exit will be a deterministic operation, such as command+Q.

OK

**Pull request merged**
